const express = require('express');
const app = express();
const port = process.env.PORT || 5000;
var bodyParser = require('body-parser')
app.use(bodyParser.json());

const Nightmare = require('nightmare')
const nightmare = Nightmare({ show: true, typeInterval: 20 })


// .click('#saveForm') replace by .goto('https://www.aegisdentalnetwork.com/admin/entries/page/6/')
app.post('/api/data-entry', (req, res) => {
  const { startDate, endDate, userName, password, channels } = req.body;
  console.log(req.body);
  nightmare
    .goto('https://www.aegisdentalnetwork.com/admin')
    .wait(3000)
    .type('body > div > form > input[type="text"]:nth-child(2)', userName)
    .type('body > div > form > input[type="password"]:nth-child(5)', password)
    .click('body > div > form > input[type="submit"]:nth-child(7)')
    .wait(3000)
    //Channel 1
    //Featured Image Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4614/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[0].title1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(2) > td:nth-child(2) > input[type="text"]', channels[0].subhead1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(5) > td:nth-child(2) > input[type="text"]', channels[0].header)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[0].link1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(8) > td:nth-child(2) > input[type="text"]', channels[0].headerLink)
    .type('#imageValue', channels[0].img)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#is_sticky')
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4614/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[0].title2)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[0].link2)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4614/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[0].title3)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[0].link3)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)
    //Channel 2
    //Feature Article
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4615/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[1].title1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(2) > td:nth-child(2) > input[type="text"]', channels[1].subhead1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(5) > td:nth-child(2) > input[type="text"]', channels[1].header)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[1].link1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(8) > td:nth-child(2) > input[type="text"]', channels[1].headerLink)
    .type('#imageValue', channels[1].img)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#is_sticky')
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4615/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[1].title2)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[1].link2)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4615/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[1].title3)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[1].link3)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Feature Article
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4616/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[2].title1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(2) > td:nth-child(2) > input[type="text"]', channels[2].subhead1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(5) > td:nth-child(2) > input[type="text"]', channels[2].header)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[2].link1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(8) > td:nth-child(2) > input[type="text"]', channels[2].headerLink)
    .type('#imageValue', channels[2].img)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#is_sticky')
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4616/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[2].title2)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[2].link2)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4616/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[2].title3)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[2].link3)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Feature Article
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4617/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[3].title1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(2) > td:nth-child(2) > input[type="text"]', channels[3].subhead1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(5) > td:nth-child(2) > input[type="text"]', channels[3].header)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[3].link1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(8) > td:nth-child(2) > input[type="text"]', channels[3].headerLink)
    .type('#imageValue', channels[3].img)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#is_sticky')
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4617/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[3].title2)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[3].link2)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4617/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[3].title3)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[3].link3)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Feature Article
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4618/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[4].title1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(2) > td:nth-child(2) > input[type="text"]', channels[4].subhead1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(5) > td:nth-child(2) > input[type="text"]', channels[4].header)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[4].link1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(8) > td:nth-child(2) > input[type="text"]', channels[4].headerLink)
    .type('#imageValue', channels[4].img)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#is_sticky')
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4618/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[4].title2)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[4].link2)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4618/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[4].title3)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[4].link3)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Feature Article
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4619/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[5].title1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(2) > td:nth-child(2) > input[type="text"]', channels[5].subhead1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(5) > td:nth-child(2) > input[type="text"]', channels[5].header)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[5].link1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(8) > td:nth-child(2) > input[type="text"]', channels[5].headerLink)
    .type('#imageValue', channels[5].img)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#is_sticky')
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4619/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[5].title2)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[5].link2)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4619/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[5].title3)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[5].link3)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Feature Article
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4620/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[6].title1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(2) > td:nth-child(2) > input[type="text"]', channels[6].subhead1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(5) > td:nth-child(2) > input[type="text"]', channels[6].header)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[6].link1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(8) > td:nth-child(2) > input[type="text"]', channels[6].headerLink)
    .type('#imageValue', channels[6].img)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#is_sticky')
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4620/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[6].title2)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[6].link2)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4620/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[6].title3)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[6].link3)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Feature Article
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4621/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[7].title1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(2) > td:nth-child(2) > input[type="text"]', channels[7].subhead1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(5) > td:nth-child(2) > input[type="text"]', channels[7].header)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[7].link1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(8) > td:nth-child(2) > input[type="text"]', channels[7].headerLink)
    .type('#imageValue', channels[7].img)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#is_sticky')
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4621/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[7].title2)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[7].link2)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4621/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[7].title3)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[7].link3)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Feature Article
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4622/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[8].title1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(2) > td:nth-child(2) > input[type="text"]', channels[8].subhead1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(5) > td:nth-child(2) > input[type="text"]', channels[8].header)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[8].link1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(8) > td:nth-child(2) > input[type="text"]', channels[8].headerLink)
    .type('#imageValue', channels[8].img)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#is_sticky')
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4622/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[8].title2)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[8].link2)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4622/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[8].title3)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[8].link3)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Feature Article
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4623/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[9].title1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(2) > td:nth-child(2) > input[type="text"]', channels[9].subhead1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(5) > td:nth-child(2) > input[type="text"]', channels[9].header)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[9].link1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(8) > td:nth-child(2) > input[type="text"]', channels[9].headerLink)
    .type('#imageValue', channels[9].img)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#is_sticky')
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4623/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[9].title2)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[9].link2)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4623/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[9].title3)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[9].link3)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Feature Article
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4624/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[10].title1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(2) > td:nth-child(2) > input[type="text"]', channels[10].subhead1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(5) > td:nth-child(2) > input[type="text"]', channels[10].header)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[10].link1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(8) > td:nth-child(2) > input[type="text"]', channels[10].headerLink)
    .type('#imageValue', channels[10].img)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#is_sticky')
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4624/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[10].title2)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[10].link2)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4624/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[10].title3)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[10].link3)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Feature Article
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4625/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[11].title1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(2) > td:nth-child(2) > input[type="text"]', channels[11].subhead1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(5) > td:nth-child(2) > input[type="text"]', channels[11].header)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[11].link1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(8) > td:nth-child(2) > input[type="text"]', channels[11].headerLink)
    .type('#imageValue', channels[11].img)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#is_sticky')
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4625/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[11].title2)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[11].link2)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4625/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[11].title3)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[11].link3)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Feature Article
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4626/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[12].title1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(2) > td:nth-child(2) > input[type="text"]', channels[12].subhead1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(5) > td:nth-child(2) > input[type="text"]', channels[12].header)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[12].link1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(8) > td:nth-child(2) > input[type="text"]', channels[12].headerLink)
    .type('#imageValue', channels[12].img)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#is_sticky')
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4626/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[12].title2)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[12].link2)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4626/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[12].title3)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[12].link3)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Feature Article
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4627/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[13].title1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(2) > td:nth-child(2) > input[type="text"]', channels[13].subhead1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(5) > td:nth-child(2) > input[type="text"]', channels[13].header)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[13].link1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(8) > td:nth-child(2) > input[type="text"]', channels[13].headerLink)
    .type('#imageValue', channels[13].img)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#is_sticky')
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4627/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[13].title2)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[13].link2)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4627/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[13].title3)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[13].link3)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Feature Article
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4628/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[14].title1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(2) > td:nth-child(2) > input[type="text"]', channels[14].subhead1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(5) > td:nth-child(2) > input[type="text"]', channels[14].header)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[14].link1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(8) > td:nth-child(2) > input[type="text"]', channels[14].headerLink)
    .type('#imageValue', channels[14].img)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#is_sticky')
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4628/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[14].title2)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[14].link2)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4628/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[14].title3)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[14].link3)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Feature Article
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4629/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[15].title1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(2) > td:nth-child(2) > input[type="text"]', channels[15].subhead1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(5) > td:nth-child(2) > input[type="text"]', channels[15].header)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[15].link1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(8) > td:nth-child(2) > input[type="text"]', channels[15].headerLink)
    .type('#imageValue', channels[15].img)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#is_sticky')
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4629/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[15].title2)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[15].link2)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4629/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[15].title3)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[15].link3)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Feature Article
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4630/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[16].title1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(2) > td:nth-child(2) > input[type="text"]', channels[16].subhead1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(5) > td:nth-child(2) > input[type="text"]', channels[16].header)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[16].link1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(8) > td:nth-child(2) > input[type="text"]', channels[16].headerLink)
    .type('#imageValue', channels[16].img)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#is_sticky')
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4630/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[16].title2)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[16].link2)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4630/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[16].title3)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[16].link3)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Feature Article
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4631/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[17].title1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(2) > td:nth-child(2) > input[type="text"]', channels[17].subhead1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(5) > td:nth-child(2) > input[type="text"]', channels[17].header)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[17].link1)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(8) > td:nth-child(2) > input[type="text"]', channels[17].headerLink)
    .type('#imageValue', channels[17].img)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#is_sticky')
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4631/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[17].title2)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[17].link2)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)

    //Non-Sticky Entry
    .goto('https://www.aegisdentalnetwork.com/admin/entries/add/4631/')
    .wait(3000)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(1) > td:nth-child(2) > input[type="text"]', channels[17].title3)
    .type('#editForm > table > tbody:nth-child(4) > tr:nth-child(7) > td:nth-child(2) > input[type="text"]', channels[17].link3)
    .click('#editForm > table > tbody:nth-child(4) > tr:nth-child(9) > td:nth-child(2) > input[type="checkbox"]')
    .type('#datefield-1020-inputEl', startDate)
    .type('#datefield-1021-inputEl', endDate)
    .click('#saveForm')
    .wait(5000)
    .end()
    .then(function (result) {
      console.log(result)
    })
    .catch(function (error) {
      console.error('Error:', error);
    });


  res.send({ express: 'Hello From Express' });

});

if (process.env.NODE_ENV === 'production') {
  //Express will serve up production assets
  //like our main.js file, or main.css file!
  app.use(express.static('client/build'));

  //Express will sever up the index.html file
  //if it doesn't recognize the route
  const path = require('path');
  app.get('*', (req, res) => {
    res.sendFile(path.resolve(__dirname, 'client', 'build', 'index.html'));
  });
}

app.listen(port, () => console.log(`Listening on port ${port}`));
